vich_uploader:
    db_driver: orm
    mappings:
        cover_image:
            uri_prefix: /images/property/cover
            upload_destination: '%kernel.project_dir%/public/images/property/cover'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false

        property_image:
            uri_prefix: /images/property/slider
            upload_destination: '%kernel.project_dir%/public/images/property/slider'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false

            
        avatar_image:
            uri_prefix: /images/agents
            upload_destination: '%kernel.project_dir%/public/images/agents'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false